version: '3'

services:
  python:
    container_name: scraping
    tty: true
    build:
      context: .
      dockerfile: ./python3/Dockerfile
    volumes:
    - .vimrc:/root/.vimrc
    - ./src:/root/src